// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaHhIufDPVVfY2fX2KLdjAoKytKRegFhw',
    appId: '1:458469369901:web:db6c45eb33937ac3acb0a4',
    messagingSenderId: '458469369901',
    projectId: 'shun-mini',
    authDomain: 'shun-mini.firebaseapp.com',
    storageBucket: 'shun-mini.appspot.com',
    measurementId: 'G-YC6BRHGTKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-NnaDqk52e_cPxxSnk6FVYEGE1szk24',
    appId: '1:458469369901:android:995087fb47f6e5aeacb0a4',
    messagingSenderId: '458469369901',
    projectId: 'shun-mini',
    storageBucket: 'shun-mini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4d9geV4LyZNhIYhzl_LQNJW4zYdN3MvY',
    appId: '1:458469369901:ios:16dd9b5b4e224984acb0a4',
    messagingSenderId: '458469369901',
    projectId: 'shun-mini',
    storageBucket: 'shun-mini.appspot.com',
    iosClientId: '458469369901-hq8u596fj5lmlc2acv5ve6nrqfevc061.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4d9geV4LyZNhIYhzl_LQNJW4zYdN3MvY',
    appId: '1:458469369901:ios:16dd9b5b4e224984acb0a4',
    messagingSenderId: '458469369901',
    projectId: 'shun-mini',
    storageBucket: 'shun-mini.appspot.com',
    iosClientId: '458469369901-hq8u596fj5lmlc2acv5ve6nrqfevc061.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMini',
  );
}
