# Generated by Django 4.1.1 on 2022-09-20 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0002_alter_twitteruser_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=180), size=20),
        ),
    ]
